### ISSUE TITLE
How to add this to 'dotnet new'?

### ISSUE THREAD

**Issue by brianjlacy** [MaximBalaganskiy/AureliaDotnetTemplate#3]
What's the most efficient way to add this template back to the `dotnet new` tooling?

**Comment by myusrn** [comment]
From what I understand using a repro clone doesn't provide support for having the project template .sln and .csproj filenames along with class namespaces automatically renamed to match the name desired for the project I want to use this as the starting point for.  

If this is considered to be a more current and improved alternative to the current "dotnet new Aurelia" provided asp.net core Aurelia spa project template enabled by "dotnet new --install Microsoft.AspNetCore.SpaTemplates::*" doesn't it make sense to have that extra step take to make in consumable in a similar way?  Even better why not issue a pull request to have your updates in this template incorporated into the official Aurelia asp.net core spa templates package?

**Comment by MaximBalaganskiy** [comment]
Because unfortunately, I don't have time for that extra step - which is not that simple. Plus, it's quite boring :) 

The official SPA templates PR won't be accepted since Aurelia project is no longer there.

**Comment by myusrn** [comment]
Thanks for details. Using 'dn new aurelia --output AureliaDotnetTemplate' to produce an Aurelia spa templates based starting project for diff'ng against clone of this repro to determine differences.  I've noticed that the current asp.net core 2.1 spa project templates [ angular & react ] have moved to using webpack instead of grunt or gulp that was used in their spa project templates in the past.  From what I can tell it appears you have stuck with the theme of using webpack task runner services also correct?

**Comment by MaximBalaganskiy** [comment]
It's been removed. The new rc1 package does not have it.

**Comment by MaximBalaganskiy** [comment]
As an option we could add a script which would rename relevant bits after cloning.

**Comment by myusrn** [comment]
fyi . . . 
w10 v1803 bld17134.48 [ april 2018 update ] + asp.net core 2.1.0 rc1 x64 / .net core sdk 2.1.300 rc1 x64 
downloaded repo and extracted contents to folder dncAurelia.alt
npm install
dotnet build
dotnet run
. . . 
fail: Microsoft.AspNetCore.NodeServices[0]
      (node:19876) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
. . .
opening listening on address in edge & chrome loads page that says "Navbar Home Counter Fetch data" across top instead of left side nav pane if intention was to mimic the Aurelia spa templates implementation.  in the case of edge clicking on counter | increment button depresses button and has it stay depressed in between clicks.  Screen grabs attached.
![screengrab1](https://user-images.githubusercontent.com/3043446/40762849-349f3a1a-6457-11e8-9a9b-8d9fb19e7f6c.png)
![screengrab2](https://user-images.githubusercontent.com/3043446/40762854-3918417c-6457-11e8-88ac-676d5c45af0b.png)

**Comment by MaximBalaganskiy** [comment]
Fixed via https://github.com/MaximBalaganskiy/AureliaDotnetTemplate/commit/87ae14616e77c193ee6739ff645d45f7995bf62d

**Comment by MaximBalaganskiy** [comment]
Please start another issue - this one has different topic
